# Generated by Django 3.2.6 on 2022-01-01 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_event_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('MAIN', 'Maintenance'), ('ACC', 'Accident'), ('REV', 'Revenue')], help_text='Event Type', max_length=150, null=True),
        ),
    ]
