# Generated by Django 3.2.6 on 2022-01-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_event_event_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('accident', 'Accident'), ('revenue', 'Revenue')], help_text='Event Type', max_length=150, null=True),
        ),
    ]
