# Generated by Django 3.2.6 on 2022-01-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost',
            field=models.IntegerField(choices=[('maintenance', 'Maintenance'), ('accident', 'Accident'), ('revenue', 'Revenue')], help_text='Cost of maintenance', null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='maintenance_type',
            field=models.CharField(choices=[('maintenance', 'Maintenance'), ('accident', 'Accident'), ('revenue', 'Revenue')], help_text='What type of maintnance', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='value',
            field=models.IntegerField(choices=[('maintenance', 'Maintenance'), ('accident', 'Accident'), ('revenue', 'Revenue')], help_text='Value of maintenance', null=True),
        ),
    ]
