# Generated by Django 3.2.6 on 2022-01-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20220102_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='maintenance_type',
            field=models.CharField(help_text='What type of maintnance', max_length=150, null=True),
        ),
    ]
