# Generated by Django 3.2.6 on 2022-01-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_event_maintenance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='cost',
            field=models.IntegerField(blank=True, help_text='Cost of maintenance', null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='value',
            field=models.IntegerField(blank=True, help_text='Value of maintenance', null=True),
        ),
    ]
