# Generated by Django 3.2.6 on 2022-01-02 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20220102_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accident', models.CharField(blank=True, help_text='Where accident occur?', max_length=150, null=True)),
                ('fault', models.CharField(blank=True, choices=[('me', 'me'), ('thirdparty', 'thirdparty')], help_text="Who's at fault?", max_length=150, null=True)),
                ('totaled', models.CharField(blank=True, help_text='Was car totaled?', max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload all images and documents related to accident', null=True, upload_to='cars')),
                ('date', models.DateField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
    ]
