# Generated by Django 3.2.6 on 2022-01-05 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_accident'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, help_text='what type of maintance?', max_length=150, null=True)),
                ('photo', models.ImageField(blank=True, help_text='Upload all images and documents related to accident', null=True, upload_to='cars')),
                ('value', models.IntegerField(blank=True, help_text='How much?', null=True)),
                ('cost', models.IntegerField(blank=True, help_text='Cost?', null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.car')),
            ],
        ),
    ]
