# Generated by Django 3.2.6 on 2022-01-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_maintenance'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='approve',
            field=models.BooleanField(blank=True, help_text='Approved?', null=True),
        ),
    ]
