# Generated by Django 3.2.6 on 2022-01-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_maintenance_approve'),
    ]

    operations = [
        migrations.AddField(
            model_name='accident',
            name='event_type',
            field=models.CharField(blank=True, default='accident', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='event_type',
            field=models.CharField(blank=True, default='maintenance', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='revenue',
            name='event_type',
            field=models.CharField(blank=True, default='revenue', max_length=150, null=True),
        ),
    ]
