# Generated by Django 3.2.6 on 2022-01-05 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20220105_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accident',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
