# Generated by Django 3.2.6 on 2022-02-11 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20220105_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='car_year',
            field=models.IntegerField(help_text='Car year', null=True),
        ),
    ]
